pipeline {
  agent {
    docker {
      image 'node:12.13.0-alpine'
      args '-p 3000:3000 --tmpfs /.npm'
    }
  }
  environment {
    CI = 'true'
  }
  stages {
    stage('Build') {
      steps {
        dir("src") {
          sh 'yarn install'
          sh 'yarn build'
        }
      }
    }
    stage('Test') {
      steps {
        dir("src") {
          sh 'yarn test'
        }
      }
    }
    stage('Publish') {
      steps {
        withNPM(npmrcConfig: 'build1-npmrc') {
          sh './bin/publish_snapshot.js ${BUILD_NUMBER}'
        }
      }
    }
  }
  post {
    always {
      slackSend(
        color: "#D4DADF",
        message: "Jenkins build started: `${env.JOB_NAME}` #${env.BUILD_NUMBER}:\n${env.RUN_DISPLAY_URL}")
    }
    failure {
      slackSend(
        color: "#FF9FA1",
        message: "Jenkins build failed: `${env.JOB_NAME}` #${env.BUILD_NUMBER}:\n${env.BUILD_URL}")
    }
  }
}
